version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bankcards_db
    environment:
      POSTGRES_DB: bankcards_db
      POSTGRES_USER: bankcards_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: always

  bankcards-app:
    image: prokopev/banckcards-app:0.0.1-SNAPSHOT
    container_name: bankcards_backend
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bankcards_db
      DB_USERNAME: bankcards_user
      DB_PASSWORD: password
      JWT_SECRET: U3UVbubDa/OhfF9c012f5EMdXKQCjmP1M9v8v4Grgj8=
    restart: always