version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bankcards_db
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bankcards_db
      DB_USERNAME: bankcards_user
      DB_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: always

  bankcards-app:
    image: prokopev/banckcards-app:0.0.1-SNAPSHOT
    container_name: bankcards_backend
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankcards_db
      SPRING_DATASOURCE_USERNAME: bankcards_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_HIKARI_CONNECTION-TIMEOUT: 30000
    restart: always