spring:
  application:
    name: bankcards
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bankcards_db}
    username: ${DB_USERNAME:bankcards_user}
    password: ${DB_PASSWORD:password}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: ${ACCESS_TOKEN_EXPIRATION:300000}
  refreshTokenExpiration: ${REFRESH_TOKEN_EXPIRATION:86400000}
  header: Authorization

bankcards:
  admin-username: ${ADMIN_USERNAME}
  admin-password: ${ADMIN_PASSWORD}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /docs/openapi.yaml
server:
  port: 8083
  servlet:
    context-path: /api/v1
