openapi: 3.0.3
info:
  title: Bankcards API
  version: 1.0.0

servers:
  - url: /api/v1

paths:
  /registration:
    post:
      tags:
        - Регистрация
      summary: "Регистрация"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
        required: true
      responses:
        "200":
          description: "OK"
        '400':
          description: "Пользователь с таким именем уже зарегистрирован"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /auth:
    post:
      tags:
        - Аутентификация
      summary: Аутентификация пользователя
      requestBody:
        description: Учетные данные пользователя
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Успешная аутентификация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /auth/refresh-token:
    post:
      tags:
        - Аутентификация
      summary: Обновление токена доступа
      description: Необходимо отправить refresh-token в заголовке Authorization
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Токены успешно обновлены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Недействительный или просроченный Refresh Token
        '500':
          description: Внутренняя ошибка сервера
  /cards:
    post:
      summary: "Создать карту"
      tags:
        - Управление картами
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCardDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CardDTO"
    get:
      summary: "Получить карты"
      tags:
        - Управление картами
      description: "Если пользователь админ, то будут выведены все карты. В случае рядового пользователя
      будут отображаться только его карты."
      parameters:
        - name: "page"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "0"
        - name: "size"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "10"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/CardDTO"
  /cards/change-status:
    patch:
      tags:
        - Управление картами
      summary: "Изменить статус карты"
      parameters:
        - name: "cardId"
          in: "query"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "newStatus"
          in: "query"
          required: true
          schema:
            type: "string"
            enum:
              - "ACTIVE"
              - "BLOCKED"
              - "EXPIRED"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CardDTO"
  /cards/{cardId}:
    delete:
      tags:
        - Управление картами
      summary: "Удалить карту"
      parameters:
        - name: "cardId"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "OK"
  /cards/{cardId}/block:
    patch:
      tags:
        - Управление картами
      summary: "Заблокировать карту"
      parameters:
        - name: "cardId"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CardDTO"
  /cards/{cardId}/balance:
    get:
      tags:
        - Управление картами
      summary: "Вывести баланс карты"
      parameters:
        - name: "cardId"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BigDecimal"
  /cards/transfer:
    post:
      tags:
        - Управление картами
      summary: "Перевод между картами"
      description: "В связи с требованиями, возможен перевод между картами относящимися одному пользователю."
      parameters:
        - name: "fromCardId"
          in: "query"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "toCardId"
          in: "query"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "amount"
          in: "query"
          required: true
          schema:
            type: string
            format: decimal
            example: "1500.50"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Void"
  /users:
    get:
      tags:
        - Пользователи
      summary: "Получить всех пользователей"
      parameters:
        - name: "page"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "0"
        - name: "size"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "10"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/UserDTO"
  /users/get:
    get:
      tags:
        - Пользователи
      summary: "Получить пользователя по ID"
      description: "При вызове данного запроса админом, он может получить любого пользователя по ID.
      Если же данные запрос вызывает пользователь, без указания id, то он получит собственные данные."
      parameters:
        - name: "id"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDTO"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    AuthRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
          format: password
    AuthResponse:
      type: object
      required:
        - accessToken
        - refreshToken
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        fullName:
          type: string
        password:
          type: string
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          example: '400'
        message:
          type: string
        timestamp:
          type: string
    CreateCardDTO:
      type: "object"
      properties:
        pan:
          type: "string"
        balance:
          type: string
          format: decimal
          example: "1500.50"
        ownerId:
          type: "string"
          format: "uuid"
        expiredAt:
          type: "string"
          format: "date"
    BigDecimal:
      type: "object"
      properties: { }
    Void:
      type: "object"
      properties: { }
    CardDTO:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        maskedPan:
          type: "string"
        status:
          type: "string"
          enum:
            - "ACTIVE"
            - "BLOCKED"
            - "EXPIRED"
        balance:
          type: string
          format: decimal
          example: "1500.50"
        expiredAt:
          type: "string"
          format: "date"
        ownerId:
          type: "string"
          format: "uuid"
    UserDTO:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        username:
          type: "string"
        fullName:
          type: "string"
security:
  - bearerAuth: []